added tests for testing database manager
go-park-mail-ru/2019_1_SleeplessNights pull request #13
Opened 2019-04-15 23:53 UTC by ALarutin

Тесты для функций AddQuestion(), AddQuestionPack(), GetQuestions(), GetPacksOfQuestions() больше затычки, потому что не понятно, как проверять их работу. Основная проблема в том, что мне нужна здесь работа с бд, запросы, которые не реализованы, типо GetQuestion(один вопрос) или  GetPackOfQuestions(один пак), но их нужно реализовывать в пакете manager.go, так как у нас закрыта бд, и то есть потом на них тоже тесты нужно чтоли писать, не совсем понятно, нужно будет обсудить. Остальные тесты норм.

2019-04-15 23:54 UTC, ALarutin commented
Да, там сейчас покрытие 75,2%

2019-04-16 08:55 UTC, maksimuimin requested changes

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +	expected := "БД: Не был найден юзер"
Здесь нужно ссылаться на константу dbManager, а не записывать стоку литералом.

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +	expected := "БД: Не был найден юзер"
Здесь аналогично - ссылка на константу

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +	expected := "pq: duplicate key value violates unique constraint \"users_email_ui\""
Сделай в dbManager публичную константу "Unique violation" и кидай её по аналогии с NoUserFound. Здесь, соответственно, нужно на неё ссылаться

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +//func TestUpdateUserUnsuccessful(t *testing.T) {
Что не получилось с этим тестом?

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +	}
Здесь можно ещё проверить, что их темы не совпадают

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +	questions, err := database.GetInstance().GetQuestions([]int{1,2,3,4})
Уверен, что этот тест всегда будет проходить? У тебя после очистки таблиц же id не с 1 начинаются. Я бы не забивал id раков константами, а достал бы из бд сначала паки, а потом вопросы

2019-04-16 08:55 UTC, DragonF0rm commented on database/manager_test.go
> +		PackID: 1,
Тут тоже PackID константа, мне кажется, что при таком подходе можешь ловить UniqueViolation. Как вариант, добавить в SQL к AddQuestionPack в конце строчку RETURNING id, чтобы после создания пака он id сразу вернул. Тогда можно будет эти два теста объединить в один и сделать пак, получить его id, и по этому id заполнить этот пак вопросами

2019-04-16 10:58 UTC, ALarutin commented on database/manager_test.go
> +	questions, err := database.GetInstance().GetQuestions([]int{1,2,3,4})
Так я при очистке скидываю считчик id, и он всегда с 1 начинается в каждом тесты.
TRUNCATE TABLE public.users, public.question, public.question_pack RESTART IDENTITY.
Вот этот в конце RESTART IDENTITY команда это делает.

2019-04-16 11:01 UTC, ALarutin commented on database/manager_test.go
> +//func TestUpdateUserUnsuccessful(t *testing.T) {
Здесь, я не понял, при каком случае у меня будет unsuccessful. Так даже если подаешь неверный id, бд не возвращает никакую ошибку, ну то есть, если мы меняем только nickname и avatarpath, то я не додумался до ситуации с ошибкой, типо если бы почту меняли, можно было бы на дубликат попасть, а так хз даже.

2019-04-16 11:17 UTC, DragonF0rm commented on database/manager_test.go
> +//func TestUpdateUserUnsuccessful(t *testing.T) {
Ну да, логично. Хотя с неверным id по идее должна быть ошибка

2019-04-16 11:18 UTC, ALarutin commented on database/manager_test.go
> +//func TestUpdateUserUnsuccessful(t *testing.T) {
Я проверял, не кидает ошибку.

2019-04-16 11:19 UTC, DragonF0rm commented on database/manager_test.go
> +	questions, err := database.GetInstance().GetQuestions([]int{1,2,3,4})
Ну ладно, тогда ок

2019-04-17 16:08 UTC, merged