Technical duty chat ms
go-park-mail-ru/2019_1_SleeplessNights pull request #28
Opened 2019-05-21 00:02 UTC by ALarutin

2019-05-21 00:03 UTC, ALarutin commented on chat_microservice/database/config.json
>    "port": 5432,
хз, вроде в gitignore есть этот конфиг, всеравно запушился

2019-05-24 14:41 UTC, maksimuimin requested changes

2019-05-24 14:41 UTC, DragonF0rm commented on chat_microservice/handlers/chat.go
> +		w.WriteHeader(http.StatusBadRequest)
Тут лучше 404, а не 400

2019-05-24 14:41 UTC, DragonF0rm commented on chat_microservice/room_manager/models.go
> +	UsersPool      map[uint64]*Talker
TODO add talkers[]

2019-05-24 14:41 UTC, DragonF0rm commented on chat_microservice/room_manager/room.go
> +	logger.Info("User ", user.Nickname, "Joined room_manager")
Check if users id exist in room.talkers

2019-05-24 14:41 UTC, DragonF0rm commented on game_microservice/game_field/game_field.go
> +	ms := payloadStr
?

2019-05-24 14:41 UTC, DragonF0rm commented on shared/services/user.proto
> +    uint64 id = 1;
//TODO add user pool

2019-05-24 20:15 UTC, ALarutin commented on game_microservice/game_field/game_field.go
> +	ms := payloadStr
Это не моё, в другом микросервисе) это надо у Макса спросить

2019-05-27 22:14 UTC, maksimuimin approved these changes

2019-05-27 22:14 UTC, merged