Added tests update profile handler
go-park-mail-ru/2019_1_SleeplessNights pull request #9
Opened 2019-03-28 22:42 UTC by ALarutin

Поднял покрытие до 68,2 %

2019-03-28 23:07 UTC, maksimuimin requested changes

2019-03-28 23:07 UTC, maksimuimin commented on handlers/helpers/auth.go
> +	secretFile, err := os.Open(os.Getenv("BASEPATH") + "secret")
Нельзя так просто влетать в код и менять какой-то путь. Со слешом всё точно работало, значит сейчас всё точно упадёт. Если у тебя в пути появилось два слеша, то это не повод менять код, ты можешь просто изменить свою переменную окружения и никакие зависимости не полетят. Верни, пожалуйста, как было.

2019-03-28 23:07 UTC, maksimuimin commented on handlers/helpers/validators.go
> +	avatarTypeWhiteList["application/octet-stream"] = struct{}{} //TODO Is it correct?
Нет, это не правильно. В спецификации написано, что это mime тип двоичного файла без описания формата, его в вайт листе быть не должно. Скорее всего, либо где-то пропущен заголовок content-type, либо в запросе идёт не настоящая аватарка, поэтому mime тип определяется неверно.

2019-03-28 23:07 UTC, maksimuimin commented on handlers/profile.go
> +		delete(models.Users, oldEmail) //TODO delete in IDmap????
Ага, похоже на правду, добавь удаление, пожалуйста.

2019-03-28 23:07 UTC, maksimuimin commented on handlers/profile.go
> +	err = avatarFile.Close()
И чем тебе defer не понравился? Вот так просто на рандоме переписывать куски кода, который писал не ты, плохая практика. Если что-то такое хочется сделать, то делай лучше как с тем удалением сверху, спроси комментарием. На ревью это все равно всплывёт.

2019-03-28 23:07 UTC, DragonF0rm commented on handlers/profile_test.go
> +	req.Header.Set("Content-Type", bodyWriter.FormDataContentType())
Возвращаясь к mime типам, вот тут посмотри, пожалуйста, тончно content-type multipart/form-data вешается?

2019-03-28 23:11 UTC, ALarutin commented on handlers/helpers/auth.go
> +	secretFile, err := os.Open(os.Getenv("BASEPATH") + "secret")
Я забыл просто вернуть это назад, я экспериментировал просто.

2019-03-28 23:13 UTC, ALarutin commented on handlers/profile.go
> +	err = avatarFile.Close()
Да там был момент один, я думал сначала, что проблема в закрытии, но оказалось, там все нормально. Опять же забыл убрать назад, но я не сильно парился, как ты говоришь, на ревью всплывет.

2019-03-28 23:15 UTC, ALarutin commented on handlers/profile_test.go
> +	req.Header.Set("Content-Type", bodyWriter.FormDataContentType())
Да, я выводил на консоль значение, там multipart/form-data, и там ещё есть boundary параметр.

2019-03-29 11:46 UTC, maksimuimin approved these changes

2019-03-29 11:46 UTC, merged